server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12     # src/main/resources에 p12 파일 복사
    key-store-password: ENC(AZD/oOYNtCPlDC68dabOeA==)
    key-store-type: PKCS12  # 인증서 형식
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  messages:
    basename: message
    encoding: utf-8
    cache-duration: 10
    fallback-to-system-locale: false
  config:
    import: optional:file:.env[.properties] #.env import
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  datasource:

    url: jdbc:mysql://127.0.0.1:3306/shopdb?serverTimezone=Asia/Seoul
    username: smuser
    password: ENC(AZD/oOYNtCPlDC68dabOeA==)
mybatis:
  type-aliases-package: edu.sm.app.dto
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    root: error

# Application Config
app:
  key:
    skey: ${MY_KEY}